//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tennis_Track.Baza_podataka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mec()
        {
            this.Sets = new HashSet<Set>();
        }
    
        public int Id { get; set; }
        public int Prvi_clan_Id { get; set; }
        public int Drugi_clan_Id { get; set; }
        public int Teren_Id { get; set; }
        public Nullable<int> Turnir_Id { get; set; }
        public System.DateTime Datum { get; set; }
        public System.TimeSpan Vrijeme { get; set; }
    
        public virtual Clan Clan { get; set; }
        public virtual Clan Clan1 { get; set; }
        public virtual Teren Teren { get; set; }
        public virtual Turnir Turnir { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Set> Sets { get; set; }

        private string imePrviClan;
        public string ImePrviClan
        {
            get { return Clan.Ime + " " + Clan.Prezime; }
            set { imePrviClan = value; }
        }


        private string imeDrugiClan;
        public string ImeDrugiClan
        {
            get { return Clan1.Ime + " " + Clan1.Prezime; }
            set { imeDrugiClan = value; }
        }


        private string vrstaTerena;
        public string VrstaTerena
        {
            get { return Teren.Vrsta; }
            set { vrstaTerena = value; }
        }

        private string imeTurnira;
        public string ImeTurnira
        {
            get { return VratiImeTurnira(); }
            set { imeTurnira = value; }
        }

        private string VratiImeTurnira()
        {
            if (Turnir == null)
                return "n/a";
            else return Turnir.Naziv;
        }

        private string rezultat;
        public string Rezultat
        {
            get { return VratiRezultatMeca(); }
            set { rezultat = value; }
        }

        private string VratiRezultatMeca()
        {
            int rezultatPrviClan = 0;
            int rezultatDrugiClan = 0;
            foreach (Set set in Sets)
            {
                if (set.Rezultat_prvi_clan > set.Rezultat_drugi_clan)
                    rezultatPrviClan = rezultatPrviClan + 1;
                else if (set.Rezultat_prvi_clan < set.Rezultat_drugi_clan)
                    rezultatDrugiClan = rezultatDrugiClan + 1;
            }


            return rezultatPrviClan.ToString() + " : " + rezultatDrugiClan.ToString();
        }
    }
}
