//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tennis_Track.Baza_podataka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervacije
    {
        public int Id { get; set; }
        public System.DateTime Datum { get; set; }
        public System.TimeSpan Vrijeme { get; set; }
        public int Clan_Id { get; set; }
        public int Teren_Id { get; set; }
    
        public virtual Clan Clan { get; set; }
        public virtual Teren Teren { get; set; }
    }
}
