//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tennis_Track.Baza_podataka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervacije
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public Nullable<System.TimeSpan> Vrijeme { get; set; }
        public Nullable<int> Clan_Id { get; set; }
        public int Teren_Id { get; set; }
    
        public virtual Clan Clan { get; set; }
        public virtual Teren Teren { get; set; }
    }
}
