//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tennis_Track.Baza_podataka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Set
    {
        public int Id { get; set; }
        public Nullable<int> Rezultat_prvi_clan { get; set; }
        public Nullable<int> Rezultat_drugi_clan { get; set; }
        public Nullable<int> Mec_Id { get; set; }
    
        public virtual Mec Mec { get; set; }
    }
}
